### ISSUE TITLE
Pre Trained weights

### ISSUE THREAD

**Issue by mugil123** [jackweiwang/high-precision_98point_faceswap#1]
Hi jack
I tried your program.
But not able to use it becase you have created a custom network layers.

It would be great if you could share the decoder and encoder files which u had used.

Appreciate it

Thanks

**Comment by jackweiwang** [comment]
Hi,  you can training by this https://github.com/shaoanlu/faceswap-GAN, 
the pre-trained model contains someone，i can't take it out.
